image: docker:latest

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  MYSQL_DATABASE: "qwest_staging_db"
  MYSQL_ROOT_PASSWORD: "1234"
  SPRING_DATASOURCE_URL: "jdbc:mysql://qwest-staging-db:3306/qwest_staging_db?useSSL=false&allowPublicKeyRetrieval=true"
  SPRING_DATASOURCE_USERNAME: "root"
  SPRING_DATASOURCE_PASSWORD: "1234"

services:
  - docker:dind

before_script:
  - chmod +x ./gradlew

stages:
  - build
  - test
  - docker

build:
  stage: build
  image: gradle:jdk17
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar
test:
  stage: test
  image: gradle:jdk17
  services:
    - name: mysql:latest
      alias: qwest-staging-db
  variables:
    SPRING_PROFILES_ACTIVE: test
  script:
    - ./gradlew test

docker:
  stage: docker
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin https://git.fhict.nl
    - docker build --pull -t $CI_REGISTRY_IMAGE/qwest-be .
    - docker push $CI_REGISTRY_IMAGE/qwest-be
