image: docker:latest

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  MYSQL_DATABASE: "qwest_staging_db"
  MYSQL_ROOT_PASSWORD: "1234"
  SPRING_DATASOURCE_URL: "jdbc:mysql://qwest-staging-db:3306/qwest_staging_db?useSSL=false&allowPublicKeyRetrieval=true"
  SPRING_DATASOURCE_USERNAME: "root"
  SPRING_DATASOURCE_PASSWORD: "1234"

services:
  - docker:dind

before_script:
  - chmod +x ./gradlew

stages:
  - build
  - test
  - deploy

build:
  stage: build
  image: gradle:jdk17
  script:
    - ls
    - pwd
    - ./gradlew assemble
    - docker build -t qwest-be .


test:
  stage: test
  image: gradle:jdk17
  services:
    - name: mysql:latest
      alias: qwest-staging-db
  variables:
    SPRING_PROFILES_ACTIVE: test
  script:
    - ls
    - pwd
    - ./gradlew test

deploy:
  stage: deploy
  script:
    - ls
    - pwd
    - docker stop qwest-be-staging
    - docker rm qwest-be-staging
    - docker run -d -p 8090:8080 --net=qwest-staging-db --env spring_profiles_active=staging --name=qwest-be-staging qwest-be
