image: docker:latest

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  MYSQL_DATABASE: "qwest_staging_db"
  MYSQL_ROOT_PASSWORD: "1234"
  SPRING_DATASOURCE_URL: "jdbc:mysql://qwest-staging-db:3306/qwest_staging_db?useSSL=false&allowPublicKeyRetrieval=true"
  SPRING_DATASOURCE_USERNAME: "root"
  SPRING_DATASOURCE_PASSWORD: "1234"

services:
  - docker:dind

before_script:
  - chmod +x ./gradlew

stages:
  - build
  - test
  - sonarqube-check

build:
  stage: build
  image: gradle:jdk17
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar
test:
  stage: test
  image: gradle:jdk17
  services:
    - name: mysql:latest
      alias: qwest-staging-db
  variables:
    SPRING_PROFILES_ACTIVE: test
  script:
    - ./gradlew test
    
sonarqube-check:
  stage: sonarqube-check
  image: gradle:jdk17
  script:
    - ./gradlew test sonar jacocoTestReport
  allow_failure: true