image: gradle:jdk17

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  MYSQL_DATABASE: "qwest_staging_db"
  MYSQL_ROOT_PASSWORD: "1234"
  SPRING_DATASOURCE_URL: "jdbc:mysql://qwest-staging-db:3306/qwest_staging_db?useSSL=false&allowPublicKeyRetrieval=true"
  SPRING_DATASOURCE_USERNAME: "root"
  SPRING_DATASOURCE_PASSWORD: "1234"
  IMAGE_NAME: "$CI_REGISTRY_IMAGE/qwest-be"

before_script:
  - chmod +x ./gradlew

stages:
  - build
  - test
  - docker

build:
  stage: build
  script:
    - ./gradlew assemble

test:
  stage: test
  services:
    - name: mysql:latest
      alias: qwest-staging-db
  variables:
    SPRING_PROFILES_ACTIVE: test
  script:
    - ./gradlew test

docker:
  stage: docker
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin https://git.fhict.nl
  script:
    - docker build -t $IMAGE_NAME .
    - docker push $IMAGE_NAME
