image: docker:19.03.12

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  MYSQL_DATABASE: "qwest_staging_db"
  MYSQL_ROOT_PASSWORD: "1234"
  SPRING_DATASOURCE_URL: "jdbc:mysql://qwest-staging-db:3306/qwest_staging_db?useSSL=false&allowPublicKeyRetrieval=true"
  SPRING_DATASOURCE_USERNAME: "root"
  SPRING_DATASOURCE_PASSWORD: "1234"
  # It's important to ensure that Docker commands are executable in the build and deploy stages
  DOCKER_HOST: tcp://docker:2375

services:
  - docker:dind
  
before_script:
- chmod +x ./gradlew

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - ./gradlew assemble
    - docker build -t $CI_REGISTRY_IMAGE/qwest-be:$CI_COMMIT_REF_SLUG .

test:
  stage: test
  script:
    - ./gradlew test

deploy:
  stage: deploy
  script:
    - docker stop qwest-be-staging || true
    - docker rm qwest-be-staging || true
    - docker run -d -p 8090:8080 --name=qwest-be-staging $CI_REGISTRY_IMAGE/qwest-be:$CI_COMMIT_REF_SLUG
