image: docker:19.03.12

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  MYSQL_DATABASE: "qwest_staging_db"
  MYSQL_ROOT_PASSWORD: "1234"
  SPRING_DATASOURCE_URL: "jdbc:mysql://qwest-staging-db:3306/qwest_staging_db?useSSL=false&allowPublicKeyRetrieval=true"
  SPRING_DATASOURCE_USERNAME: "root"
  SPRING_DATASOURCE_PASSWORD: "1234"
  # Ensure IMAGE_NAME is properly formatted. Replace '/' with '-' in CI_PROJECT_PATH if necessary.
  IMAGE_NAME: "${CI_REGISTRY_IMAGE}/${CI_PROJECT_PATH,,}:${CI_COMMIT_REF_SLUG}"

services:
  - docker:19.03.12-dind

stages:
  - build
  - test
  - docker

before_script:
  - apk add --no-cache openjdk17
  - chmod +x ./gradlew
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build:
  stage: build
  image: gradle:jdk17
  script:
    - ./gradlew assemble

test:
  stage: test
  image: gradle:jdk17
  services:
    - name: mysql:latest
      alias: qwest-staging-db
  variables:
    SPRING_PROFILES_ACTIVE: test
  script:
    - ./gradlew test

docker:
  stage: docker
  script:
    - docker build --pull -t "$IMAGE_NAME" .
    - docker push "$IMAGE_NAME"
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        docker tag "$IMAGE_NAME" "$CI_REGISTRY_IMAGE:latest"
        docker push "$CI_REGISTRY_IMAGE:latest"
      fi
  rules:
    - if: $CI_COMMIT_BRANCH
      exists:
        - Dockerfile
