image: docker:19.03.12

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  MYSQL_DATABASE: "qwest_staging_db"
  MYSQL_ROOT_PASSWORD: "1234"
  SPRING_DATASOURCE_URL: "jdbc:mysql://qwest-staging-db:3306/qwest_staging_db?useSSL=false&allowPublicKeyRetrieval=true"
  SPRING_DATASOURCE_USERNAME: "root"
  SPRING_DATASOURCE_PASSWORD: "1234"
  # Simplified and more generic image name
  IMAGE_NAME: "${CI_REGISTRY_IMAGE}/qwest-app:latest"

services:
  - docker:19.03.12-dind

before_script:
  - chmod +x ./gradlew

stages:
  - build
  - test
  - docker

build:
  stage: build
  image: gradle:jdk17
  script:
    - ./gradlew assemble

test:
  stage: test
  image: gradle:jdk17
  services:
    - name: mysql:latest
      alias: qwest-staging-db
  variables:
    SPRING_PROFILES_ACTIVE: test
  script:
    - ./gradlew test

docker:
  stage: docker
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin https://git.fhict.nl
    - docker build --pull -t "$IMAGE_NAME" .
    - docker push "$IMAGE_NAME"
