image: gradle:jdk17

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  MYSQL_DATABASE: "qwest_staging_db"
  MYSQL_ROOT_PASSWORD: "1234"
  SPRING_DATASOURCE_URL: "jdbc:mysql://qwest-staging-db:3306/qwest_staging_db?useSSL=false&allowPublicKeyRetrieval=true"
  SPRING_DATASOURCE_USERNAME: "root"
  SPRING_DATASOURCE_PASSWORD: "1234"
  IMAGE_TAG: "${CI_REGISTRY_IMAGE}/${CI_PROJECT_PATH,,}:${CI_COMMIT_REF_SLUG}"

before_script:
  - chmod +x ./gradlew

stages:
  - build
  - test
  - docker_build
  - docker_push

build:
  stage: build
  script:
    - ./gradlew assemble

test:
  stage: test
  services:
    - name: mysql:latest
      alias: qwest-staging-db
  variables:
    SPRING_PROFILES_ACTIVE: test
  script:
    - ./gradlew test

docker_build:
  stage: docker_build
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  script:
    - docker build -t $IMAGE_TAG .

docker_push:
  stage: docker_push
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  script:
    - echo "Deploying image $IMAGE_TAG"
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $IMAGE_TAG
