image: docker:latest

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  MYSQL_DATABASE: "qwest_staging_db"
  MYSQL_ROOT_PASSWORD: "1234"
  SPRING_DATASOURCE_URL: "jdbc:mysql://qwest-staging-db:3306/qwest_staging_db?useSSL=false&allowPublicKeyRetrieval=true"
  SPRING_DATASOURCE_USERNAME: "root"
  SPRING_DATASOURCE_PASSWORD: "1234"

services:
  - docker:dind

before_script:
  - chmod +x ./gradlew

stages:
  - docker

docker:
  stage: docker
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin https://git.fhict.nl
    - docker build --pull -t $CI_REGISTRY/I499309/qwest-be:$CI_COMMIT_REF_SLUG .
    - docker push $CI_REGISTRY/I499309/qwest-be:$CI_COMMIT_REF_SLUG
