version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ../qwest-fe
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../qwest-fe:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
