version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: staging
    env_file:
      - .env
    depends_on:
      - qwest-staging-db
    networks:
      - qwest-network

  frontend:
    build:
      context: ../qwest-fe
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - qwest-network

  qwest-staging-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: qwest_staging_db
    ports:
      - "3369:3306"
    networks:
      - qwest-network

networks:
  qwest-network:
    external: true
